<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KncWX2Server.Protocol</AssemblyName>
    <RootNamespace>KncWX2Server.Protocol</RootNamespace>
    <EventIdGeneratedFile>$(MSBuildProjectDirectory)/Generated/EventId.generated.cs</EventIdGeneratedFile>
  </PropertyGroup>

  <Target Name="GenerateEventIds" BeforeTargets="CoreCompile">
    <MakeDir Directories="$(MSBuildProjectDirectory)/Generated" />
    <Exec Command="dotnet run --project &quot;$(MSBuildProjectDirectory)/../EventIdGenerator/EventIdGenerator.csproj&quot; --configuration Release -- &quot;$(MSBuildProjectDirectory)/../../KncWX2Server/Common/EventID_Client.h&quot; &quot;$(MSBuildProjectDirectory)/../../KncWX2Server/Common/OnlyGlobal/EventID_Client_Global.h&quot; &quot;$(MSBuildProjectDirectory)/../../KncWX2Server/Common/EventID_Server.h&quot; &quot;$(EventIdGeneratedFile)&quot;" />
  </Target>
</Project>
