#pragma once

class CX2ViewerMain;

#define RP_SIZE_X	600
#define RP_SIZE_Y	500

class CX2ViewerUI : public CX2ViewerObject
{
	public:
		enum MESH_SEL
		{
			MS_NONE = 0,
			MS_SKIN_MESH,
			MS_MESH,
		};

		enum UI_ID
		{
			//--Base Option
			UI_CHECK_GRID	= 0,
			UI_CHECK_WIREFRAME,
			UI_BUT_RESET,
			UI_BUT_UI_INIT,
			UI_STATIC_CAMERAMODE,
			UI_RADIO_CAMERA_NORMAL,
			UI_RADIO_CAMERA_NAVIGATION,
			UI_BUT_CAMERA_RESET,
			UI_STATIC_BGSET,
			UI_STATIC_BG_A,
			UI_STATIC_BG_R,
			UI_STATIC_BG_G,
			UI_STATIC_BG_B,
			UI_EDIT_BG_A,
			UI_EDIT_BG_R,
			UI_EDIT_BG_G,
			UI_EDIT_BG_B,

			UI_STATIC_WORLD_MESH,
			UI_BUT_WORLD_MESH,
			UI_BUT_WORLD_MESH_RESET,
			UI_STATIC_WORLD_MESH_X,
			UI_STATIC_WORLD_MESH_Y,
			UI_STATIC_WORLD_MESH_Z,
			UI_EDIT_WORLD_MESH_X,
			UI_EDIT_WORLD_MESH_Y,
			UI_EDIT_WORLD_MESH_Z,

			UI_BUT_EFFECT_SET,
            
			//Base Option--

			//--Unit
			UI_STATIC_SCALE,
			UI_STATIC_SCALE_X,
			UI_STATIC_SCALE_Y,
			UI_STATIC_SCALE_Z,
			UI_EDIT_SCALE_X,
			UI_EDIT_SCALE_Y,
			UI_EDIT_SCALE_Z,

			UI_STATIC_LIGHT_POS,
			UI_STATIC_LIGHT_POS_X,
			UI_STATIC_LIGHT_POS_Y,
			UI_STATIC_LIGHT_POS_Z,
			UI_EDIT_LIGHT_POS_X,
			UI_EDIT_LIGHT_POS_Y,
			UI_EDIT_LIGHT_POS_Z,
			UI_CHECK_LIGHT_ONOFF,

			UI_STATIC_OBJECT,
			UI_LIST_OBJECT,
			UI_STATIC_ANIMATION,
			UI_LIST_ANIMATION,
            UI_LIST_BONE,
			UI_EDIT_ANIM_NUM,
			UI_EDIT_ANIM_NAME,

			UI_BUT_ATTACH_WEAPON,            
			UI_EDIT_ATTACH_WEAPON_BONE_NAME,
			UI_STATIC_ATTACH_WEAPON_BONE_NAME,

			UI_BUT_ANIM_NAME_CHANGE,

			UI_STATIC_WEAPON_ROT_X,
			UI_EDIT_WEAPON_ROT_X,
			UI_STATIC_WEAPON_ROT_Y,
			UI_EDIT_WEAPON_ROT_Y,
			UI_STATIC_WEAPON_ROT_Z,
			UI_EDIT_WEAPON_ROT_Z,

			UI_BUT_PLAY_ONOFF,
			UI_STATIC_ANIM_SPEED,
			UI_SLIDE_ANIM_SPEED,
			UI_STATIC_ANIM_FRAME,
			UI_CHECK_MOTION_ONOFF,
			UI_BUT_RENDER_PARAM,

			UI_STATIC_PLAY_TYPE,
			UI_COMBO_PLAY_TYPE,

			UI_CHECK_BOUNDING,
			UI_CHECK_ATTACK_BOX,
			
			UI_EDIT_FRAME_TIME_INC,
			UI_BUT_PREV_FRAME,
			UI_BUT_NEXT_FRAME,
			
            UI_BUT_ATTACH_ACCESSORY,            
            UI_EDIT_ATTACH_ACCESSORY_BONE_NAME,
            UI_STATIC_ATTACH_ACCESSORY_BONE_NAME,

            UI_STATIC_ACCESSORY_TRANS_X,
            UI_EDIT_ACCESSORY_TRANS_X,
            UI_STATIC_ACCESSORY_TRANS_Y,
            UI_EDIT_ACCESSORY_TRANS_Y,
            UI_STATIC_ACCESSORY_TRANS_Z,
            UI_EDIT_ACCESSORY_TRANS_Z,

            UI_STATIC_ACCESSORY_SCALE,             
            UI_EDIT_ACCESSORY_SCALE_X, 
            UI_EDIT_ACCESSORY_SCALE_Y, 
            UI_EDIT_ACCESSORY_SCALE_Z, 

            UI_STATIC_ACCESSORY_ROTATE,              
            UI_EDIT_ACCESSORY_ROTATE_X,  
            UI_EDIT_ACCESSORY_ROTATE_Y,  
            UI_EDIT_ACCESSORY_ROTATE_Z,  


			//Unit--

			//--Mesh
			UI_STATIC_MESH_SCALE,
			UI_STATIC_MESH_SCALE_X,
			UI_STATIC_MESH_SCALE_Y,
			UI_STATIC_MESH_SCALE_Z,
			UI_EDIT_MESH_SCALE_X,
			UI_EDIT_MESH_SCALE_Y,
			UI_EDIT_MESH_SCALE_Z,

			UI_STATIC_MESH_LIGHT_POS,
			UI_STATIC_MESH_LIGHT_POS_X,
			UI_STATIC_MESH_LIGHT_POS_Y,
			UI_STATIC_MESH_LIGHT_POS_Z,
			UI_EDIT_MESH_LIGHT_POS_X,
			UI_EDIT_MESH_LIGHT_POS_Y,
			UI_EDIT_MESH_LIGHT_POS_Z,
			UI_CHECK_MESH_LIGHT_ONOFF,

			UI_BUT_MESH_RENDER_PARAM,
			//Mesh--

			//--Render Param
			UI_STATIC_RENDERTYPE,
			UI_COMBO_RENDERTYPE,

			UI_STATIC_CARTOON_TEX_TYPE,
			UI_COMBO_CARTOON_TEX_TYPE,

			UI_STATIC_OUTLINE_WIDE,
			UI_EDIT_OUTLINE_WIDE,

			UI_STATIC_OUTLINE_COLOR,
			UI_STATIC_OUTLINE_COLOR_A,
			UI_STATIC_OUTLINE_COLOR_R,
			UI_STATIC_OUTLINE_COLOR_G,
			UI_STATIC_OUTLINE_COLOR_B,
			UI_EDIT_OUTLINE_COLOR_A,
			UI_EDIT_OUTLINE_COLOR_R,
			UI_EDIT_OUTLINE_COLOR_G,
			UI_EDIT_OUTLINE_COLOR_B,

			UI_STATIC_COLOR,
			UI_STATIC_COLOR_A,
			UI_STATIC_COLOR_R,
			UI_STATIC_COLOR_G,
			UI_STATIC_COLOR_B,
			UI_EDIT_COLOR_A,
			UI_EDIT_COLOR_R,
			UI_EDIT_COLOR_G,
			UI_EDIT_COLOR_B,

			UI_STATIC_LIGHTFLOW_WIDE,
			UI_EDIT_LIGHTFLOW_WIDE,

			UI_STATIC_LIGHTFLOW_IMPACT,
			UI_STATIC_LIGHTFLOW_IMPACT_MIN,
			UI_STATIC_LIGHTFLOW_IMPACT_MAX,
			UI_STATIC_LIGHTFLOW_IMPACT_ANIMTIME,
			UI_EDIT_LIGHTFLOW_IMPACT_MIN,
			UI_EDIT_LIGHTFLOW_IMPACT_MAX,
			UI_EDIT_LIGHTFLOW_IMPACT_ANIMTIME,

			UI_STATIC_LIGHTFLOW_POINT,
			UI_STATIC_LIGHTFLOW_POINT_X,
			UI_STATIC_LIGHTFLOW_POINT_Y,
			UI_STATIC_LIGHTFLOW_POINT_Z,
			UI_EDIT_LIGHTFLOW_POINT_X,
			UI_EDIT_LIGHTFLOW_POINT_Y,
			UI_EDIT_LIGHTFLOW_POINT_Z,

			UI_STATIC_TEXOFFSET_STAGE0,
			UI_STATIC_TEXOFFSET_STAGE0_X,
			UI_STATIC_TEXOFFSET_STAGE0_Y,
			UI_STATIC_TEXOFFSET_STAGE0_MIN,
			UI_STATIC_TEXOFFSET_STAGE0_MAX,
			UI_STATIC_TEXOFFSET_STAGE0_ANIMTIME,
			UI_EDIT_TEXOFFSET_STAGE0_MIN_X,
			UI_EDIT_TEXOFFSET_STAGE0_MIN_Y,
			UI_EDIT_TEXOFFSET_STAGE0_MAX_X,
			UI_EDIT_TEXOFFSET_STAGE0_MAX_Y,
			UI_EDIT_TEXOFFSET_STAGE0_ANIMTIME,

			UI_STATIC_TEXOFFSET_STAGE1,
			UI_STATIC_TEXOFFSET_STAGE1_X,
			UI_STATIC_TEXOFFSET_STAGE1_Y,
			UI_STATIC_TEXOFFSET_STAGE1_MIN,
			UI_STATIC_TEXOFFSET_STAGE1_MAX,
			UI_STATIC_TEXOFFSET_STAGE1_ANIMTIME,
			UI_EDIT_TEXOFFSET_STAGE1_MIN_X,
			UI_EDIT_TEXOFFSET_STAGE1_MIN_Y,
			UI_EDIT_TEXOFFSET_STAGE1_MAX_X,
			UI_EDIT_TEXOFFSET_STAGE1_MAX_Y,
			UI_EDIT_TEXOFFSET_STAGE1_ANIMTIME,

			UI_STATIC_TEXOFFSET_STAGE2,
			UI_STATIC_TEXOFFSET_STAGE2_X,
			UI_STATIC_TEXOFFSET_STAGE2_Y,
			UI_STATIC_TEXOFFSET_STAGE2_MIN,
			UI_STATIC_TEXOFFSET_STAGE2_MAX,
			UI_STATIC_TEXOFFSET_STAGE2_ANIMTIME,
			UI_EDIT_TEXOFFSET_STAGE2_MIN_X,
			UI_EDIT_TEXOFFSET_STAGE2_MIN_Y,
			UI_EDIT_TEXOFFSET_STAGE2_MAX_X,
			UI_EDIT_TEXOFFSET_STAGE2_MAX_Y,
			UI_EDIT_TEXOFFSET_STAGE2_ANIMTIME,

			UI_STATIC_ALPHA_BLEND,
			UI_COMBO_ALPHA_BLEND,

			UI_STATIC_ZENABLE,
			UI_COMBO_ZENABLE,

			UI_STATIC_CULLMODE,
			UI_COMBO_CULLMODE,

			UI_STATIC_SRCBLEND,
			UI_COMBO_SRCBLEND,

			UI_STATIC_DESTBLEND,
			UI_COMBO_DESTBLEND,

			UI_BUT_PARAM_OK,
			UI_BUT_PARAM_CANCEL,
           
			//Render Param--

			// Particle Basic
			UI_LIST_PARTICLE_LIST,
			UI_BUT_PARTICLE_DELETE,
			
			UI_STATIC_PARTICLE_TIME,
			UI_EDIT_PARTICLE_TIME,

			UI_BUT_PARTICLE_BONESET,
			UI_BUT_PARTICLE_BONECLEAR,
			UI_CHECK_PARTICLE_TRACE,

			UI_STATIC_PARTICLE_OFFSET,
			UI_EDIT_PARTICLE_OFFSET_X,
			UI_EDIT_PARTICLE_OFFSET_Y,
			UI_EDIT_PARTICLE_OFFSET_Z,
			UI_CHECK_PARTICLE_LANDPOS,

			UI_STATIC_PARTICLE_ROT,
			UI_EDIT_PARTICLE_ROT_X,
			UI_EDIT_PARTICLE_ROT_Y,
			UI_EDIT_PARTICLE_ROT_Z,
			UI_CHECK_PARTICLE_APPUNITROT, 

			UI_BUT_PARTICLE_SAVESEQUENCE,

			UI_BUT_PARTICLE_PARTICLEEDITOR,
			// Particle Basic--

			// Particle Editor
			UI_LIST_PARTICLE_EDITOR_MYPARTICLE,
			UI_BUT_PARTICLE_EDITOR_MYPARTICLE_LOAD,
			UI_BUT_PARTICLE_EDITOR_MYPARTICLE_DELETE,
			UI_BUT_PARTICLE_EDITOR_MYPARTICLE_SAVE,

			UI_LIST_PARTICLE_EDITOR_PARTICLETEMPLET,
			UI_BUT_PARTICLE_EDITOR_PARTICLETEMPLET_COPY,
			UI_BUT_PARTICLE_EDITOR_PARTICLETEMPLET_RELOAD,

			UI_STATIC_PARTICLE_EDITOR_EMITTERATTRIBUTE,
			UI_LIST_PARTICLE_EDITOR_EMITTERATTRIBUTE,
			UI_STATIC_PARTICLE_EDITOR_EMITTERATTRIBUTE_VALUE,
			UI_EDIT_PARTICLE_EDITOR_EMITTERATTRIBUTE_SINGLE,
			UI_EDIT_PARTICLE_EDITOR_EMITTERATTRIBUTE_X,
			UI_EDIT_PARTICLE_EDITOR_EMITTERATTRIBUTE_Y,
			UI_EDIT_PARTICLE_EDITOR_EMITTERATTRIBUTE_Z,
			UI_COMBO_PARTICLE_EDITOR_EMITTERATTRIBUTE,
			UI_BUT_PARTICLE_EDITOR_EMITTERATTRIBUTE_APPLY,
			
			UI_LIST_PARTICLE_EDITOR_EVENT,			//
			UI_BUT_PARTICLE_EDITOR_EVENT_DELETE,

			UI_STATIC_PARTICLE_EDITOR_EVENT_TYPE,
			UI_LIST_PARTICLE_EDITOR_EVENT_TYPE,		//
			UI_STATIC_PARTICLE_EDITOR_EVENT_TIME,
			UI_CHECK_PARTICLE_EDITOR_EVENT_FADE,
			UI_STATIC_PARTICLE_EDITOR_EVENT_FROM,
			UI_STATIC_PARTICLE_EDITOR_EVENT_TO,
			UI_EDIT_PARTICLE_EDITOR_EVENT_TIME1,
			UI_EDIT_PARTICLE_EDITOR_EVENT_TIME2,
			UI_STATIC_PARTICLE_EDITOR_EVENT_VALUE,
			UI_EDIT_PARTICLE_EDITOR_EVENT_SINGLE,
			UI_EDIT_PARTICLE_EDITOR_EVENT_X,
			UI_EDIT_PARTICLE_EDITOR_EVENT_Y,
			UI_EDIT_PARTICLE_EDITOR_EVENT_Z,
			UI_COMBO_PARTICLE_EDITOR_EVENT,
			UI_EDIT_PARTICLE_EDITOR_EVENT_R,
			UI_EDIT_PARTICLE_EDITOR_EVENT_G,
			UI_EDIT_PARTICLE_EDITOR_EVENT_B,
			UI_EDIT_PARTICLE_EDITOR_EVENT_A,
			UI_BUT_PARTICLE_EDITOR_EVENT_APPLY,			
			UI_BUT_PARTICLE_EDITOR_EVENT_NEW,
			
			UI_LIST_PARTICLE_EDITOR_MODEL_LIST,
			UI_BUT_PARTICLE_EDITOR_MODEL_ADD,
			UI_BUT_PARTICLE_EDITOR_MODEL_DELETE,

			UI_STATIC_PARTICLE_EDITOR_PLAY_TYPE,
			UI_COMBO_PARTICLE_EDITOR_PLAY_TYPE,
			UI_BUT_PARTICLE_EDITOR_PLAY,

			UI_STATIC_PARTICLE_EDITOR_SPEED,
			UI_SLIDE_PARTICLE_EDITOR_SPEED,
			UI_STATIC_PARTICLE_EDITOR_TIME,

			UI_BUT_PARTICLE_EDITOR_EXIT,
			// Particle Editor--

		};

        std::vector<CKTDXDeviceXSkinMesh::MultiAnimFrame *> m_vecFrameNameList;

	public:
		CX2ViewerUI(CX2ViewerMain* pMain);
		virtual ~CX2ViewerUI(void);

		virtual HRESULT OnFrameMove( double fTime, float fElapsedTime );
		virtual HRESULT OnFrameRender();

		virtual bool MsgProc( HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam );

		virtual HRESULT OnResetDevice();
		virtual HRESULT OnLostDevice();

		void	SetUnitOnOff( bool bOnOff ){ m_Unit.SetVisible( bOnOff ); }
		void	SetMeshOnOff( bool bOnOff ){ m_Mesh.SetVisible( bOnOff ); }
		void	SetRenderParamOnOff( bool bIsParam )
		{ 
			m_RenderParam.SetVisible( bIsParam );
			m_Param.SetParamDlg( &m_RenderParam ); 
		}
		void	SetEffectButOnOff( bool bIsOnOff )
		{
			m_BaseOption.GetButton( UI_BUT_EFFECT_SET )->SetVisible( bIsOnOff );
		}
		void	SetParticleButOnOff( bool bIsOnOff ){ m_ParticleBasic.SetVisible( bIsOnOff ); }
		
		void	SetParticleEditButOnOff( bool bIsOnOff ){ m_ParticleEditor.SetVisible(bIsOnOff); }

		void DropFile( std::wstring fileName,std::wstring dir );

		float	GetAnimTimeInc() const { return m_fAnimTimeInc; }
		void	SetAnimTimeInc(float val) { m_fAnimTimeInc = val; }

        CKTDXDeviceXSkinMesh::MultiAnimFrame *GetFrameList(int inx) { return m_vecFrameNameList[inx]; }

	private:
		static	void CALLBACK OnGUIEvent( UINT nEvent, int nControlID, CDXUTControl* pControl, void* pUserContext );
		static	void CALLBACK OnGUIUnitEvent( UINT nEvent, int nControlID, CDXUTControl* pControl, void* pUserContext );
		static	void CALLBACK OnGUIMeshEvent( UINT nEvent, int nControlID, CDXUTControl* pControl, void* pUserContext );
		static	void CALLBACK OnGUIRPEvent( UINT nEvent, int nControlID, CDXUTControl* pControl, void* pUserContext );
		static	void CALLBACK OnGUIParticleEvent( UINT nEvent, int nControlID, CDXUTControl* pControl, void* pUserContext );
		static	void CALLBACK OnGUIParticleEditorEvent( UINT nEvent, int nControlID, CDXUTControl* pControl, void* pUserContext );
		

		void Init();
		void DrawAnimFrame();
		void DrawParticleTime();
		void InitAnimSpeed();

		// 파티클 에디터 관련
		void InitParticleEditor();	// 파티클 에디터 초기화 관련 코드. 정리겸 해서 따로 뺌.
		void RefreshEventList();

	private:
		static	CX2ViewerUI*	ms_pSelfInstance;

		CDXUTDialog		m_BaseOption;
		CDXUTDialog		m_Unit;
		CDXUTDialog		m_Mesh;
		CDXUTDialog		m_RenderParam;
		
		CDXUTDialog		m_ParticleBasic;		// 모델뷰 모드에서 표시되는 파티클 관련 UI들
		CDXUTDialog		m_ParticleEditor;		// 파티클 수정 모드 UI들

		CX2ViewerParam	m_Param;
		CX2ViewerFileOS	m_FileOS;

		bool			m_bIsInit;
		float			m_fElapsedTime;
		CX2ViewerMain*	m_pMain;

		MESH_SEL		m_MeshSel;

		std::vector<CDXUTDialog*>	m_vecDialog;

		float			m_fAnimTimeInc;
};
