#nullable enable

using System.Text;
using System.Text.RegularExpressions;

if (args.Length < 6)
{
    Console.Error.WriteLine("usage: EventIdGenerator <system-header> <client-header> <client-global-header> <server-header> <output> <profile>");
    return 2;
}

var systemPath = Path.GetFullPath(args[0]);
var clientPath = Path.GetFullPath(args[1]);
var globalPath = Path.GetFullPath(args[2]);
var serverPath = Path.GetFullPath(args[3]);
var outputPath = Path.GetFullPath(args[4]);
var profilePath = Path.GetFullPath(args[5]);

RequireFile(systemPath, "Native EventID_System.h");
RequireFile(clientPath, "Native EventID_Client.h");
RequireFile(globalPath, "Native EventID_Client_Global.h");
RequireFile(serverPath, "Native EventID_Server.h");
RequireFile(profilePath, "EventID macro profile");

var profileName = Path.GetFileNameWithoutExtension(profilePath);
var systemSource = TranslateEnumSource(systemPath, "E_SYSTEM_EVENT_ID_END");
var clientSource = string.Concat(
    TranslateEnumSource(clientPath, "E_CLIENT_EVENT_ID_BEGIN", "EGS_CLIENT_EVENT_ID_END"),
    TranslateEnumSource(globalPath, "EGS_CLIENT_EVENT_ID_END"));
var serverSource = TranslateEnumSource(serverPath, "E_SERVER_EVENT_ID_BEGIN", "E_SERVER_EVENT_ID_END");

ValidateNonEmpty(systemSource, "system");
ValidateNonEmpty(clientSource, "client/global");
ValidateNonEmpty(serverSource, "server");

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine($"// Native EventID declarations translated with conditional branches preserved. Profile: {profileName}");
sb.AppendLine("// Effective numeric values follow the C# preprocessor configuration used by the Protocol project.");
sb.AppendLine("#nullable enable");
sb.AppendLine("namespace KncWX2Server.Protocol;");
sb.AppendLine();

AppendEnum(sb, "SystemEventId", systemSource, null, "E_SYSTEM_EVENT_ID_END");
sb.AppendLine();
AppendEnum(sb, "ClientEventId", clientSource, "(ushort)SystemEventId.E_SYSTEM_EVENT_ID_END", "EGS_CLIENT_EVENT_ID_END");
sb.AppendLine();
AppendEnum(sb, "ServerEventId", serverSource, "(ushort)ClientEventId.EGS_CLIENT_EVENT_ID_END", "E_SERVER_EVENT_ID_END");
sb.AppendLine();
AppendEnum(sb, "X2ServerEventId", clientSource, "(ushort)SystemEventId.E_SYSTEM_EVENT_ID_END", "EGS_CLIENT_EVENT_ID_END", "EVENT_X2_STARTUP");
sb.AppendLine();

sb.AppendLine("internal static class GeneratedEventIdRanges");
sb.AppendLine("{");
sb.AppendLine("    public const ushort SystemBoundary = (ushort)SystemEventId.E_SYSTEM_EVENT_ID_END;");
sb.AppendLine("    public const ushort ClientStart = (ushort)SystemEventId.E_SYSTEM_EVENT_ID_END + 1;");
sb.AppendLine("    public const ushort ClientEnd = (ushort)ClientEventId.EGS_CLIENT_EVENT_ID_END;");
sb.AppendLine("    public const ushort ServerBoundary = (ushort)ClientEventId.EGS_CLIENT_EVENT_ID_END;");
sb.AppendLine("    public const ushort ServerStart = (ushort)ServerEventId.E_SERVER_EVENT_ID_BEGIN + 1;");
sb.AppendLine("    public const ushort ServerEnd = (ushort)ServerEventId.E_SERVER_EVENT_ID_END;");
sb.AppendLine("}");
sb.AppendLine();

sb.AppendLine("internal static class GeneratedEventIdNames");
sb.AppendLine("{");
sb.AppendLine("    public static string? Get(ushort value)");
sb.AppendLine("    {");
sb.AppendLine("        if (value == (ushort)X2ServerEventId.EVENT_X2_STARTUP)");
sb.AppendLine("            return nameof(X2ServerEventId.EVENT_X2_STARTUP);");
sb.AppendLine();
sb.AppendLine("        if (Enum.IsDefined(typeof(ClientEventId), value))");
sb.AppendLine("            return ((ClientEventId)value).ToString();");
sb.AppendLine();
sb.AppendLine("        if (Enum.IsDefined(typeof(ServerEventId), value))");
sb.AppendLine("            return ((ServerEventId)value).ToString();");
sb.AppendLine();
sb.AppendLine("        if (Enum.IsDefined(typeof(SystemEventId), value))");
sb.AppendLine("            return ((SystemEventId)value).ToString();");
sb.AppendLine();
sb.AppendLine("        return null;");
sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated conditional EventID source. Profile={profileName}; output={outputPath}");
return 0;

static void AppendEnum(
    StringBuilder sb,
    string enumName,
    string members,
    string? beginExpression,
    string trailingSentinel,
    string? startupName = null)
{
    sb.AppendLine($"public enum {enumName} : ushort");
    sb.AppendLine("{");

    if (startupName is not null)
        sb.AppendLine($"    {startupName} = (ushort)SystemEventId.E_SYSTEM_EVENT_ID_END,");

    if (beginExpression is not null)
    {
        var beginName = enumName switch
        {
            "ClientEventId" => "E_CLIENT_EVENT_ID_BEGIN",
            "ServerEventId" => "E_SERVER_EVENT_ID_BEGIN",
            _ => null,
        };

        if (beginName is not null)
            sb.AppendLine($"    {beginName} = {beginExpression},");
    }

    sb.Append(members);
    sb.AppendLine($"    {trailingSentinel},");
    sb.AppendLine("}");
}

static string TranslateEnumSource(string path, params string[] skip)
{
    var skipped = skip.ToHashSet(StringComparer.Ordinal);
    var builder = new StringBuilder();
    var enumRegex = new Regex(@"_ENUM\s*\(\s*(?<value>[^\)]*)\)", RegexOptions.Compiled);
    var directiveRegex = new Regex(@"^\s*#\s*(?<directive>[A-Za-z_][A-Za-z0-9_]*)(?:\s+(?<argument>.*?))?\s*$", RegexOptions.Compiled);

    foreach (var rawLine in File.ReadLines(path))
    {
        var line = rawLine.TrimEnd();
        var directive = directiveRegex.Match(line);
        if (directive.Success)
        {
            var name = directive.Groups["directive"].Value;
            var argument = directive.Groups["argument"].Value.Trim();

            switch (name)
            {
                case "ifdef":
                    builder.AppendLine($"#if {argument}");
                    break;
                case "ifndef":
                    builder.AppendLine($"#if !{argument}");
                    break;
                case "if":
                    builder.AppendLine($"#if {TranslateCondition(argument)}");
                    break;
                case "elif":
                    builder.AppendLine($"#elif {TranslateCondition(argument)}");
                    break;
                case "else":
                case "endif":
                    builder.AppendLine($"#{name}");
                    break;
                case "include":
                case "define":
                case "undef":
                case "pragma":
                    break;
                default:
                    throw new InvalidOperationException($"Unsupported native preprocessor directive '#{name}' in '{path}'.");
            }

            continue;
        }

        var trimmed = line.Trim();
        if (trimmed is "enum" or "{" or "};" or "}")
            continue;

        var match = enumRegex.Match(line);
        if (!match.Success)
            continue;

        var value = match.Groups["value"].Value.Trim();
        var nameOnly = value.Split('=', 2)[0].Trim();
        if (nameOnly.Length == 0 || skipped.Contains(nameOnly))
            continue;

        var replacement = value.Contains('=')
            ? value + ","
            : nameOnly + ",";

        builder.AppendLine(enumRegex.Replace(line, replacement, 1));
    }

    return builder.ToString();
}

static string TranslateCondition(string expression)
{
    var translated = Regex.Replace(expression, @"!\s*defined\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", "!$1");
    translated = Regex.Replace(translated, @"defined\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", "$1");
    translated = Regex.Replace(translated, @"!\s*defined\s+([A-Za-z_][A-Za-z0-9_]*)", "!$1");
    translated = Regex.Replace(translated, @"defined\s+([A-Za-z_][A-Za-z0-9_]*)", "$1");
    translated = Regex.Replace(translated, @"(?<![A-Za-z0-9_])0(?![A-Za-z0-9_])", "false");
    translated = Regex.Replace(translated, @"(?<![A-Za-z0-9_])1(?![A-Za-z0-9_])", "true");
    return translated.Trim();
}

static void RequireFile(string path, string description)
{
    if (!File.Exists(path))
        throw new FileNotFoundException($"{description} was not found.", path);
}

static void ValidateNonEmpty(string source, string range)
{
    if (string.IsNullOrWhiteSpace(source))
        throw new InvalidOperationException($"No {range} EventID declarations were found after translation.");
}
