#nullable enable

using System.Text;
using System.Text.RegularExpressions;

if (args.Length < 3)
{
    Console.Error.WriteLine("usage: EventIdGenerator <client-header> <output> <global-header>");
    return 2;
}

var clientPath = Path.GetFullPath(args[0]);
var outputPath = Path.GetFullPath(args[1]);
var globalPath = Path.GetFullPath(args[2]);

RequireFile(clientPath, "Native EventID_Client.h");
RequireFile(globalPath, "Native EventID_Client_Global.h");

var names = new List<string>();
ReadEnumNames(clientPath, names);
ReadEnumNames(globalPath, names);

if (names.Count == 0)
    throw new InvalidOperationException("No client event IDs were found in the native headers.");

if (names[0] != "EGS_GOOD_JOB_1_REQ")
    throw new InvalidOperationException($"Unexpected first client event ID: {names[0]}");

var duplicates = names
    .GroupBy(static name => name, StringComparer.Ordinal)
    .Where(static group => group.Count() > 1)
    .Select(static group => group.Key)
    .ToArray();

if (duplicates.Length != 0)
    throw new InvalidOperationException($"Duplicate EventID names: {string.Join(", ", duplicates)}");

const int startup = 20;
var firstClientId = startup + 1;
var clientEnd = firstClientId + names.Count;

if (clientEnd > ushort.MaxValue)
    throw new InvalidOperationException($"EventID range exceeds UInt16: {clientEnd}");

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("#nullable enable");
sb.AppendLine("namespace KncWX2Server.Protocol;");
sb.AppendLine();
sb.AppendLine("public enum ServerEventId : ushort");
sb.AppendLine("{");
sb.AppendLine($"    EVENT_X2_STARTUP = {startup},");
for (var i = 0; i < names.Count; i++)
    sb.AppendLine($"    {names[i]} = {firstClientId + i},");
sb.AppendLine($"    EGS_CLIENT_EVENT_ID_END = {clientEnd},");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("internal static class GeneratedEventIdNames");
sb.AppendLine("{");
sb.AppendLine("    public static string? Get(ushort value) => value switch");
sb.AppendLine("    {");
sb.AppendLine($"        {startup} => nameof(ServerEventId.EVENT_X2_STARTUP),");
for (var i = 0; i < names.Count; i++)
    sb.AppendLine($"        {firstClientId + i} => nameof(ServerEventId.{names[i]}),");
sb.AppendLine($"        {clientEnd} => nameof(ServerEventId.EGS_CLIENT_EVENT_ID_END),");
sb.AppendLine("        _ => null,");
sb.AppendLine("    };");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated {names.Count} client/global event IDs; startup={startup}, clientStart={firstClientId}, clientEnd={clientEnd}.");
return 0;

static void RequireFile(string path, string description)
{
    if (!File.Exists(path))
        throw new FileNotFoundException($"{description} was not found.", path);
}

static void ReadEnumNames(string path, List<string> names)
{
    var regex = new Regex(@"^\s*_ENUM\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", RegexOptions.Compiled);
    foreach (var line in File.ReadLines(path))
    {
        var match = regex.Match(line);
        if (!match.Success)
            continue;

        var name = match.Groups[1].Value;
        if (name is "E_SYSTEM_EVENT_ID_END" or "EGS_CLIENT_EVENT_ID_END")
            continue;
        names.Add(name);
    }
}
