#nullable enable

using System.Text;
using System.Text.RegularExpressions;

if (args.Length < 4)
{
    Console.Error.WriteLine("usage: EventIdGenerator <client-header> <global-header> <server-header> <output>");
    return 2;
}

var clientPath = Path.GetFullPath(args[0]);
var globalPath = Path.GetFullPath(args[1]);
var serverPath = Path.GetFullPath(args[2]);
var outputPath = Path.GetFullPath(args[3]);

RequireFile(clientPath, "Native EventID_Client.h");
RequireFile(globalPath, "Native EventID_Client_Global.h");
RequireFile(serverPath, "Native EventID_Server.h");

var clientNames = ReadEnumNames(clientPath);
clientNames.AddRange(ReadEnumNames(globalPath));
var serverNames = ReadEnumNames(serverPath);

RequireFirst(clientNames, "EGS_GOOD_JOB_1_REQ", "client");
RequireNotEmpty(serverNames, "server");
ValidateUniqueNames(clientNames, "client/global");
ValidateUniqueNames(serverNames, "server");
ValidateNoOverlap(clientNames, serverNames);

const int systemBoundary = 20;
var clientStart = systemBoundary + 1;
var clientEnd = clientStart + clientNames.Count;
var serverBoundary = clientEnd;
var serverStart = serverBoundary + 1;
var serverEnd = serverStart + serverNames.Count;

ValidateRange(clientEnd, "client END");
ValidateRange(serverEnd, "server END");

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Generated from the native declaration-space headers. Feature-gated native build configurations may select subsets of these declarations.");
sb.AppendLine("#nullable enable");
sb.AppendLine("namespace KncWX2Server.Protocol;");
sb.AppendLine();

sb.AppendLine("/// <summary>Declared native ENUM_CLIENT_EVENT_ID range.</summary>");
sb.AppendLine("public enum ClientEventId : ushort");
sb.AppendLine("{");
sb.AppendLine($"    E_CLIENT_EVENT_ID_BEGIN = {systemBoundary},");
AppendEnumMembers(sb, clientNames, clientStart);
sb.AppendLine($"    EGS_CLIENT_EVENT_ID_END = {clientEnd},");
sb.AppendLine("}");
sb.AppendLine();

sb.AppendLine("/// <summary>Declared native ENUM_SERVER_EVENT_ID range from EventID_Server.h.</summary>");
sb.AppendLine("public enum ServerEventId : ushort");
sb.AppendLine("{");
sb.AppendLine($"    E_SERVER_EVENT_ID_BEGIN = {serverBoundary},");
AppendEnumMembers(sb, serverNames, serverStart);
sb.AppendLine("}");
sb.AppendLine();

sb.AppendLine("/// <summary>Native X2ServerEvent union: startup plus client/global declarations.</summary>");
sb.AppendLine("public enum X2ServerEventId : ushort");
sb.AppendLine("{");
sb.AppendLine($"    EVENT_X2_STARTUP = {systemBoundary},");
AppendEnumMembers(sb, clientNames, clientStart);
sb.AppendLine($"    EGS_CLIENT_EVENT_ID_END = {clientEnd},");
sb.AppendLine("}");
sb.AppendLine();

sb.AppendLine("internal static class GeneratedEventIdNames");
sb.AppendLine("{");
sb.AppendLine("    public static string? Get(ushort value) => value switch");
sb.AppendLine("    {");
sb.AppendLine($"        {systemBoundary} => nameof(X2ServerEventId.EVENT_X2_STARTUP),");
AppendNameCases(sb, clientNames, clientStart, "ClientEventId");
sb.AppendLine($"        {clientEnd} => nameof(ClientEventId.EGS_CLIENT_EVENT_ID_END),");
AppendNameCases(sb, serverNames, serverStart, "ServerEventId");
sb.AppendLine("        _ => null,");
sb.AppendLine("    };");
sb.AppendLine("}");
sb.AppendLine();

sb.AppendLine("internal static class GeneratedEventIdRanges");
sb.AppendLine("{");
sb.AppendLine($"    public const ushort ClientStart = {clientStart};");
sb.AppendLine($"    public const ushort ClientEnd = {clientEnd};");
sb.AppendLine($"    public const ushort ServerStart = {serverStart};");
sb.AppendLine($"    public const ushort ServerEnd = {serverEnd};");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated client={clientNames.Count}, server={serverNames.Count}; client={clientStart}..{clientEnd - 1}, server={serverStart}..{serverEnd - 1}, serverBoundary={serverBoundary}.");
return 0;

static void AppendEnumMembers(StringBuilder sb, IReadOnlyList<string> names, int start)
{
    for (var i = 0; i < names.Count; i++)
        sb.AppendLine($"    {names[i]} = {start + i},");
}

static void AppendNameCases(StringBuilder sb, IReadOnlyList<string> names, int start, string enumName)
{
    for (var i = 0; i < names.Count; i++)
        sb.AppendLine($"        {start + i} => nameof({enumName}.{names[i]}),");
}

static List<string> ReadEnumNames(string path)
{
    var regex = new Regex(@"^\s*_ENUM\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", RegexOptions.Compiled);
    var names = new List<string>();

    foreach (var line in File.ReadLines(path))
    {
        var match = regex.Match(line);
        if (!match.Success)
            continue;

        var name = match.Groups[1].Value;
        if (name is "E_SYSTEM_EVENT_ID_END" or "EGS_CLIENT_EVENT_ID_END" or "E_CLIENT_EVENT_ID_BEGIN" or "E_SERVER_EVENT_ID_BEGIN")
            continue;
        names.Add(name);
    }

    return names;
}

static void RequireFile(string path, string description)
{
    if (!File.Exists(path))
        throw new FileNotFoundException($"{description} was not found.", path);
}

static void RequireFirst(IReadOnlyList<string> names, string expected, string range)
{
    if (names.Count == 0 || names[0] != expected)
        throw new InvalidOperationException($"Unexpected first {range} EventID: {names.FirstOrDefault() ?? "<none>"}.");
}

static void RequireNotEmpty(IReadOnlyList<string> names, string range)
{
    if (names.Count == 0)
        throw new InvalidOperationException($"No {range} EventIDs were found in the native header.");
}

static void ValidateUniqueNames(IEnumerable<string> names, string range)
{
    var duplicates = names
        .GroupBy(static name => name, StringComparer.Ordinal)
        .Where(static group => group.Count() > 1)
        .Select(static group => group.Key)
        .ToArray();

    if (duplicates.Length != 0)
        throw new InvalidOperationException($"Duplicate {range} EventID names: {string.Join(", ", duplicates)}");
}

static void ValidateNoOverlap(IEnumerable<string> clientNames, IEnumerable<string> serverNames)
{
    var clientSet = clientNames.ToHashSet(StringComparer.Ordinal);
    var overlap = serverNames.Where(clientSet.Contains).ToArray();

    if (overlap.Length != 0)
        throw new InvalidOperationException($"EventID names appear in both client and server ranges: {string.Join(", ", overlap)}");
}

static void ValidateRange(int endExclusive, string description)
{
    if (endExclusive > ushort.MaxValue)
        throw new InvalidOperationException($"EventID {description} exceeds UInt16: {endExclusive}");
}
