CREATE TABLE IF NOT EXISTS GUser (
    UserUID INTEGER NOT NULL,
    UserID TEXT NOT NULL,
    USSize INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    DelDate TEXT NOT NULL,
    Deleted INTEGER GENERATED ALWAYS AS (
        CASE WHEN RegDate = DelDate THEN 0 ELSE 1 END
    ) STORED
);

CREATE INDEX IF NOT EXISTS ix_GUser_UserUID ON GUser(UserUID);
CREATE INDEX IF NOT EXISTS ix_GUser_UserID ON GUser(UserID);
