CREATE TABLE IF NOT EXISTS GUnit (
    UnitUID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    UserUID INTEGER NOT NULL,
    UnitClass INTEGER NOT NULL,
    Exp INTEGER NOT NULL,
    Level INTEGER NOT NULL,
    GamePoint INTEGER NOT NULL,
    VSPoint INTEGER NOT NULL,
    VSPointMax INTEGER NULL,
    BaseHP INTEGER NOT NULL,
    AtkPhysic INTEGER NOT NULL,
    AtkMagic INTEGER NOT NULL,
    DefPhysic INTEGER NOT NULL,
    DefMagic INTEGER NOT NULL,
    SPoint INTEGER NOT NULL,
    Win INTEGER NOT NULL,
    Lose INTEGER NOT NULL,
    Seceder INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    DelDate TEXT NOT NULL,
    LastDate TEXT NOT NULL,
    LastPosition INTEGER NOT NULL,
    PlayDayCnt INTEGER NOT NULL,
    LoginCount INTEGER NOT NULL,
    Deleted INTEGER GENERATED ALWAYS AS (
        CASE WHEN RegDate = DelDate THEN 0 ELSE 1 END
    ) STORED
);

CREATE INDEX IF NOT EXISTS ix_GUnit_UserUID ON GUnit(UserUID);
CREATE INDEX IF NOT EXISTS ix_GUnit_Deleted ON GUnit(Deleted);
