CREATE TABLE IF NOT EXISTS GItem (
    ItemUID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    UnitUID INTEGER NOT NULL,
    ItemID INTEGER NOT NULL,
    InventoryCategory INTEGER NOT NULL,
    SlotID INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    DelDate TEXT NOT NULL,
    Deleted INTEGER GENERATED ALWAYS AS (
        CASE WHEN RegDate = DelDate THEN 0 ELSE 1 END
    ) STORED
);

CREATE INDEX IF NOT EXISTS ix_GItem_UnitUID ON GItem(UnitUID);
CREATE INDEX IF NOT EXISTS ix_GItem_ItemID ON GItem(ItemID);
CREATE INDEX IF NOT EXISTS ix_GItem_Deleted ON GItem(Deleted);
