CREATE TABLE IF NOT EXISTS GSkill (
    UnitUID INTEGER NOT NULL,
    SkillID INTEGER NOT NULL,
    RegDate TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_GSkill_UnitUID ON GSkill(UnitUID);
CREATE INDEX IF NOT EXISTS ix_GSkill_SkillID ON GSkill(SkillID);
