CREATE TABLE IF NOT EXISTS GSkillSlot (
    UnitUID INTEGER NOT NULL,
    Slot01 INTEGER NOT NULL,
    Slot02 INTEGER NOT NULL,
    Slot03 INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_GSkillSlot_UnitUID ON GSkillSlot(UnitUID);
