CREATE TABLE IF NOT EXISTS GSpirit (
    unitUID INTEGER NOT NULL,
    Spirit INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    Flag INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_GSpirit_unitUID ON GSpirit(unitUID);
