CREATE TABLE IF NOT EXISTS GItemSocket (
    ItemUID INTEGER NOT NULL,
    Socket1 INTEGER NOT NULL,
    Socket2 INTEGER NOT NULL,
    Socket3 INTEGER NOT NULL,
    Socket4 INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_GItemSocket_ItemUID ON GItemSocket(ItemUID);
