CREATE TABLE IF NOT EXISTS GQuests (
    UnitUID INTEGER NOT NULL,
    QuestID INTEGER NOT NULL,
    SubQuest0 INTEGER NOT NULL,
    SubQuest1 INTEGER NOT NULL,
    SubQuest2 INTEGER NOT NULL,
    SubQuest3 INTEGER NOT NULL,
    SubQuest4 INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    PRIMARY KEY (UnitUID, QuestID)
);
CREATE INDEX IF NOT EXISTS ix_GQuests_UnitUID ON GQuests(UnitUID);
