CREATE TABLE IF NOT EXISTS GPetPromotion (Promotion INTEGER NOT NULL PRIMARY KEY, Name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS GPet (PetUID INTEGER NOT NULL, LoginUID INTEGER NOT NULL, PetID INTEGER NOT NULL, PetName TEXT NOT NULL, Promotion INTEGER NOT NULL, FullTime INTEGER NOT NULL DEFAULT 0, RegDate TEXT NOT NULL, PRIMARY KEY (PetUID, LoginUID, PetID), FOREIGN KEY (Promotion) REFERENCES GPetPromotion(Promotion));
CREATE TABLE IF NOT EXISTS GPetExp (PetUID INTEGER NOT NULL, Promotion INTEGER NOT NULL, Exp INTEGER NOT NULL, PRIMARY KEY (PetUID, Promotion));
CREATE TABLE IF NOT EXISTS GPetNameLog (PetUID INTEGER NOT NULL, OldPetName TEXT NOT NULL, NewPetName TEXT NOT NULL, RegDate TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS GPetLog (PetUID INTEGER NOT NULL, LoginUID INTEGER NOT NULL, PetID INTEGER NOT NULL, PetName TEXT NOT NULL, Promotion INTEGER NOT NULL, Exp INTEGER NOT NULL, FullTime INTEGER NOT NULL, RegDate TEXT NOT NULL, DelDate TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ix_GPet_LoginUID ON GPet(LoginUID);
CREATE INDEX IF NOT EXISTS ix_GPetExp_PetUID ON GPetExp(PetUID);