CREATE TABLE IF NOT EXISTS GPetEquip (PetUID INTEGER NOT NULL, ItemUID INTEGER NOT NULL, ItemType INTEGER NOT NULL, PRIMARY KEY (PetUID, ItemUID, ItemType), FOREIGN KEY (PetUID) REFERENCES GPet(PetUID));
CREATE INDEX IF NOT EXISTS ix_GPetEquip_PetUID ON GPetEquip(PetUID);
CREATE TABLE IF NOT EXISTS GPetItem (PetID INTEGER NOT NULL, Promotion INTEGER NOT NULL, ItemID INTEGER NOT NULL, ItemType INTEGER NOT NULL, Factor INTEGER NOT NULL, PRIMARY KEY (PetID, Promotion, ItemID, ItemType));
CREATE INDEX IF NOT EXISTS ix_GPetItem_PetID ON GPetItem(PetID);