CREATE TABLE IF NOT EXISTS GRecommend (OldUID INTEGER NOT NULL, NewUID INTEGER NOT NULL, RegDate TEXT NULL);
CREATE INDEX IF NOT EXISTS IX_GRecommend_NewUID ON GRecommend(NewUID);
CREATE INDEX IF NOT EXISTS IX_GRecommend_OldUID ON GRecommend(OldUID);
