CREATE TABLE IF NOT EXISTS GBlacklist (
    MyUID INTEGER NOT NULL,
    BlockUID INTEGER NOT NULL,
    PRIMARY KEY (MyUID, BlockUID)
);

CREATE INDEX IF NOT EXISTS ix_GBlacklist_BlockUID ON GBlacklist(BlockUID);
