CREATE TABLE IF NOT EXISTS GSkill (
    UnitUID INTEGER NOT NULL,
    SkillID INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    PRIMARY KEY (UnitUID, SkillID),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID)
);
CREATE TABLE IF NOT EXISTS GSkillSlot (
    UnitUID INTEGER NOT NULL PRIMARY KEY,
    Slot01 INTEGER NOT NULL,
    Slot02 INTEGER NOT NULL,
    Slot03 INTEGER NOT NULL,
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID)
);
CREATE TABLE IF NOT EXISTS GDenyOption (
    UnitUID INTEGER NOT NULL,
    QuestionNo INTEGER NOT NULL,
    CodeNo INTEGER NOT NULL,
    PRIMARY KEY (UnitUID, QuestionNo),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID)
);
CREATE TABLE IF NOT EXISTS GQuests (
    UnitUID INTEGER NOT NULL,
    QuestID INTEGER NOT NULL,
    SubQuest0 INTEGER NOT NULL,
    SubQuest1 INTEGER NOT NULL,
    SubQuest2 INTEGER NOT NULL,
    SubQuest3 INTEGER NOT NULL,
    SubQuest4 INTEGER NOT NULL,
    RegDate TEXT NOT NULL,
    PRIMARY KEY (UnitUID, QuestID),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID)
);
