CREATE TABLE IF NOT EXISTS GItem (
    ItemUID INTEGER PRIMARY KEY AUTOINCREMENT,
    UnitUID INTEGER NOT NULL,
    ItemID INTEGER NOT NULL,
    InventoryCategory INTEGER NOT NULL DEFAULT 0,
    SlotID INTEGER NOT NULL DEFAULT 0,
    RegDate TEXT NOT NULL,
    DelDate TEXT NOT NULL,
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID)
);
CREATE INDEX IF NOT EXISTS IX_GItem_UnitUID_Deleted ON GItem(UnitUID, DelDate, RegDate);
CREATE TABLE IF NOT EXISTS GItemPeriod (
    ItemUID INTEGER PRIMARY KEY,
    Period INTEGER NOT NULL,
    ExpirationDate TEXT NOT NULL,
    FOREIGN KEY (ItemUID) REFERENCES GItem(ItemUID)
);
CREATE TABLE IF NOT EXISTS GItemEndurance (
    ItemUID INTEGER PRIMARY KEY,
    Endurance INTEGER NOT NULL,
    FOREIGN KEY (ItemUID) REFERENCES GItem(ItemUID)
);
CREATE TABLE IF NOT EXISTS GItemQuantity (
    ItemUID INTEGER PRIMARY KEY,
    Quantity INTEGER NOT NULL,
    FOREIGN KEY (ItemUID) REFERENCES GItem(ItemUID)
);
CREATE TABLE IF NOT EXISTS GItemEnchant (
    ItemUID INTEGER PRIMARY KEY,
    Elevel INTEGER NOT NULL,
    FOREIGN KEY (ItemUID) REFERENCES GItem(ItemUID)
);
