CREATE TABLE IF NOT EXISTS GItemSocket (
    ItemUID INTEGER NOT NULL PRIMARY KEY,
    Socket1 INTEGER NOT NULL DEFAULT 0,
    Socket2 INTEGER NOT NULL DEFAULT 0,
    Socket3 INTEGER NOT NULL DEFAULT 0,
    Socket4 INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (ItemUID) REFERENCES GItem(ItemUID)
);
