CREATE TABLE IF NOT EXISTS GDungeonClear (
    UnitUID INTEGER NOT NULL,
    GameMode INTEGER NOT NULL,
    MaxScore INTEGER NOT NULL DEFAULT 0,
    MaxTotalRank INTEGER NOT NULL DEFAULT 0,
    RegDate TEXT NOT NULL,
    PRIMARY KEY (UnitUID, GameMode),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID)
);
CREATE INDEX IF NOT EXISTS IX_GDungeonClear_UnitUID ON GDungeonClear(UnitUID);
